name: CI/CD 
on: 
 push: 
   branches: 
      - main 
      - cicd_413031 
pull_request: 
branches: 
      - main 
      - cicd_413031 
permissions: 
contents: read 
jobs: 
test-on-linux: 
   runs-on: ubuntu-latest 
steps: 
      - 
      - 
      - 
name: Checkout code 
uses: actions/checkout@v3 
name: Set up Python 3.10 
uses: actions/setup-python@v3 
   with: 
python-version: "3.10" 
architecture: x64 
name: Run tests 
 run: python.exe -m unittest circle.py rectangle.py square.py triangle.py
  test-on-windows: 
runs-on: windows-latest 
steps: 
      - 
      - 
      - 
name: Checkout code 
uses: actions/checkout@v3 
name: Set up Python 3.10 
uses: actions/setup-python@v3 
with: 
python-version: "3.10" 
architecture: x64 
name: Run tests 
  run: python.exe -m unittest circle.py rectangle.py square.py triangle.py 